### ISSUE TITLE
코드 리뷰 확인 부탁드립니다

### ISSUE THREAD

**Issue by wngml02** [SongGaHyeon/Git_practice_for_2022#2]
입력받는 값의 변수 이름도 함께 출력 요청합니다.
day1 = input("day1: ")
9048447

**Comment by SongGaHyeon** [comment]
입력받는 값의 변수 이름 출력 완료했습니다. 감사합니다 😉

**Comment by SongGaHyeon** [comment]
입력받는 값의 변수 이름 출력 완료했습니다. 감사합니다 😉
